runtime: nodejs20

handlers:
  # Ruta para servir el archivo index.html
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  # Ruta para servir archivos est치ticos generados por Vite
  - url: /assets
    static_dir: dist/assets

  # Ruta para servir otros archivos est치ticos (evitar que sean tratados como redirecci칩n a index.html)
  - url: /(.+\..+)
    static_files: dist/\1
    upload: dist/(.+)

  # Redirigir todas las dem치s rutas (por ejemplo, las rutas gestionadas por React Router) a index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
